name: signsafe
services:
  signsafe.backend:
    image: eduardoeckert/sign-safe-backend:latest
    container_name: signsafe.backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - DB_HOST=signsafe.database
      - DB_NAME=SignSafe
      - DB_SA_PASSWORD=Password2019! 
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=signSafePassword
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/signsafe.pfx
    build:
      context: .
      dockerfile: src/SignSafe.Presentation/Dockerfile
    ports:
      - 8080:8080
      # - 8081:8081
    networks:
      - signsafenetwork
    depends_on:
      - signsafe.database
    # volumes:
    #   - ./RunSetup/certificates:/https

  signsafe.frontend:
    image: eduardoeckert/sign-safe-frontend:latest
    container_name: signsafe.frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    build:
      context: ./Front/signsafe
      dockerfile: Dockerfile
    ports:
      - 9090:5173
    command: ["npm", "run", "dev"]
    depends_on:
      - signsafe.backend

  signsafe.database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: signsafe.database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password2019!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - signsafenetwork
    volumes:
      - sqlvolume:/var/opt/mssql 

  signsafe.seq:
    image: datalust/seq:latest
    container_name: signsafe.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8082:80
    networks:
      - signsafenetwork

networks:
  signsafenetwork:    
    driver: bridge

volumes:
  sqlvolume: