version: '3.4'

services:
  signsafe.presentation:
    image: ${DOCKER_REGISTRY-}signsafepresentation
    container_name: signsafe.api
    build:
      context: .
      dockerfile: SignSafe.Presentation/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - signsafenetwork
    depends_on:
      - signsafe.database

  signsafe.database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: signsafe.database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password2019!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - signsafenetwork
    volumes:
      - sqlvolume:/var/opt/mssql 

networks:
  signsafenetwork:    
    driver: bridge

volumes:
  sqlvolume: