services:
  signsafe.presentation:
    image: eduardoeckert/sign-safe-api
    container_name: signsafe.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - DB_HOST=signsafe.database
      - DB_NAME=SignSafe
      - DB_SA_PASSWORD=Password2019! 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=signSafePassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/signsafe.pfx
    build:
      context: .
      dockerfile: SignSafe.Presentation/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - signsafenetwork
    depends_on:
      - signsafe.database

  signsafe.database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: signsafe.database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password2019!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - signsafenetwork
    volumes:
      - sqlvolume:/var/opt/mssql 

networks:
  signsafenetwork:    
    driver: bridge

volumes:
  sqlvolume: